version: '2'
services:

  db:
    image: mysql:5.7
    ports:
      - "33306:3306"
    environment:
      MYSQL_USER: sequeltest
      MYSQL_PASSWORD: sequeltest
      MYSQL_ROOT_PASSWORD: sequeltest
      MYSQL_DATABASE: sequeltest

  web:
    build:
      context: .
    links:
      - db
